I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 106, in script
    Zeil "Oh, the basketball team is playing?"
Exception: Sayer 'Zeil' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 106, in script
    Zeil "Oh, the basketball team is playing?"
  File "C:\Users\David\Downloads\renpy-8.2.3-sdk\renpy\ast.py", line 2560, in execute
    Say.execute(self)
  File "C:\Users\David\Downloads\renpy-8.2.3-sdk\renpy\ast.py", line 575, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\David\Downloads\renpy-8.2.3-sdk\renpy\ast.py", line 464, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'Zeil' is not defined.

Windows-10-10.0.22000 AMD64
Ren'Py 8.2.3.24061702
SaveTheDate 1.0
Sat Jul 13 18:16:15 2024
